# Remove the version line or update it
services:
  credit-risk-api-v2:
    build:
      context: .
      dockerfile: Dockerfile_2
    container_name: credit-risk-api-v2
    ports:
      - "8001:8001"
    environment:
      MODEL_LOCAL_PATH: /app/models/simple_working_model.joblib
      MODEL_FEATURES_PATH: /app/models/feature_names_simple.json
      LOG_LEVEL: INFO
      PYTHONPATH: /app/src_2
    volumes:
      - ./models:/app/models:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
